<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>
  <ItemGroup>
    <!-- Once published: <PackageReference Include="OpenMBEE.SysML" Version="..." /> -->
    <ProjectReference Include="..\..\csharp\OpenMBEE.SysML\OpenMBEE.SysML.csproj" />
  </ItemGroup>
</Project>
