<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <LangVersion>latest</LangVersion>
    <RootNamespace>OpenMBEE.SysML.Checks</RootNamespace>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OpenMBEE.SysML\OpenMBEE.SysML.csproj" />
  </ItemGroup>

</Project>
