"""Generate ToolkitTable.g.cs in the C# project (tools/naming.py): dispatch data for the C#
SysML Toolkit backend. Same inputs and result codes as tools/gen_toolkit_table.py.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

from naming import CS_NAMESPACE, CS_PROJECT, abi_params, op_key, result_code

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DEFAULT_TABLES = ROOT / "vendor" / "naming-table"  # vendored; see its PIN.json
OUT = CS_PROJECT / "ToolkitTable.g.cs"

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tables", type=Path, default=DEFAULT_TABLES)
    a = ap.parse_args()
    raw = (a.tables / "toolkit-api-names.csv").read_bytes()
    digest = hashlib.sha256(raw.replace(b"\r\n", b"\n")).hexdigest()
    rows = list(csv.DictReader(raw.decode("utf-8").splitlines()))
    # Properties are keyed by name, operations by name + "()": `instantiatedType` is both a
    # property and an operation of the same class, and each keeps its row.
    for r in rows:
        r["key"] = op_key(r["member"]) if r["kind"] == "operation" else r["member"]
    mm = json.loads((ROOT / "metamodel.json").read_text(encoding="utf-8"))

    out = [
        "// Generated by tools/gen_toolkit_table_cs.py. Do not edit.",
        "using System.Collections.Generic;",
        "",
        f"namespace {CS_NAMESPACE};",
        "",
        "/// <summary>Dispatch data for <see cref=\"ToolkitBackend\"/>: spec member to C symbol, result code and,",
        "/// for an operation, its parameters' C types joined by ';'; plus bases.</summary>",
        "internal static class ToolkitTable",
        "{",
        f'    public const string NamesDigest = "{digest}";',
        "    public static readonly Dictionary<string, (string Symbol, char Code, string Params)> Funcs = new()",
        "    {",
    ]
    for r in rows:
        out.append(f'        ["{r["declaring_class"]}::{r["key"]}"] = ("sysmlv2_{r["rust_fn"]}", \'{result_code(r)}\', "{";".join(abi_params(r))}"),')
    out += ["    };", "    public static readonly Dictionary<string, string[]> Bases = new()", "    {"]
    for name, rec in sorted(mm["classes"].items()):
        arr = ", ".join(f'"{b}"' for b in rec["bases"])
        out.append(f'        ["{name}"] = new[] {{ {arr} }},' if arr else f'        ["{name}"] = System.Array.Empty<string>(),')
    out += ["    };", "}", ""]
    OUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}: {len(rows)} functions, {len(mm['classes'])} classes, digest {digest[:12]}")


if __name__ == "__main__":
    main()
