"""Generate ToolkitTable.java in the Java package (tools/naming.py): the dispatch data the
Java SysML Toolkit backend needs. Same inputs and same result codes as tools/gen_toolkit_table.py.

Chunked static initialisers keep every method under the JVM's 64 KB bytecode limit.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

from naming import JAVA_PACKAGE, JAVA_SRC, abi_params, op_key, result_code

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DEFAULT_TABLES = ROOT / "vendor" / "naming-table"  # vendored; see its PIN.json
OUT = JAVA_SRC / "ToolkitTable.java"

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tables", type=Path, default=DEFAULT_TABLES)
    a = ap.parse_args()
    raw = (a.tables / "toolkit-api-names.csv").read_bytes()
    digest = hashlib.sha256(raw.replace(b"\r\n", b"\n")).hexdigest()
    rows = list(csv.DictReader(raw.decode("utf-8").splitlines()))
    # Properties are keyed by name, operations by name + "()": `instantiatedType` is both a
    # property and an operation of the same class, and each keeps its row.
    for r in rows:
        r["key"] = op_key(r["member"]) if r["kind"] == "operation" else r["member"]
    mm = json.loads((ROOT / "metamodel.json").read_text(encoding="utf-8"))

    j = [
        "// Generated by tools/gen_toolkit_table_java.py. Do not edit.",
        f"package {JAVA_PACKAGE};",
        "",
        "import java.util.HashMap;",
        "import java.util.Map;",
        "",
        "/** Dispatch data for {@link ToolkitBackend}: spec member to C symbol, result code and, for an",
        " * operation, its parameters' C types joined by ';'; plus bases. */",
        "final class ToolkitTable {",
        f'    static final String NAMES_DIGEST = "{digest}";',
        "    static final Map<String, String[]> FUNCS = new HashMap<>();",
        "    static final Map<String, String[]> BASES = new HashMap<>();",
        "    private ToolkitTable() {}",
    ]
    chunks = [rows[i:i + 150] for i in range(0, len(rows), 150)]
    for n, chunk in enumerate(chunks):
        j.append(f"    private static void funcs{n}() {{")
        for r in chunk:
            j.append(f'        FUNCS.put("{r["declaring_class"]}::{r["key"]}", '
                     f'new String[] {{"sysmlv2_{r["rust_fn"]}", "{result_code(r)}", "{";".join(abi_params(r))}"}});')
        j.append("    }")
    j.append("    private static void bases() {")
    for name, rec in sorted(mm["classes"].items()):
        arr = ", ".join(f'"{b}"' for b in rec["bases"])
        j.append(f'        BASES.put("{name}", new String[] {{{arr}}});')
    j.append("    }")
    j.append("    static {")
    for n in range(len(chunks)):
        j.append(f"        funcs{n}();")
    j.append("        bases();")
    j.append("    }")
    j.append("}")
    OUT.write_text("\n".join(j) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT}: {len(rows)} functions, {len(mm['classes'])} classes, digest {digest[:12]}")


if __name__ == "__main__":
    main()
