"""Generate sysml/toolkit_table.py: the dispatch data the Python SysML Toolkit backend needs.

Inputs: the naming table (vendor/naming-table/, or --tables) and metamodel.json.
Output: two dictionaries.

  FUNCS[(declaring_class, key)] = (c_symbol, result_code, params)
      key: the member name for a property, the name + "()" for an operation
      result_code: H = handle array, R = single handle, S = string, T = list of strings (JSON
                   text in a string), B = bool, I = int, F = real; see naming.result_code
      params: tuple of (name, c_type) for operations, empty for properties;
              c_type is Str, Handle, Handles or bool, matching tools/gen_abi.py
  BASES[class] = [direct base classes]      (to find the declaring class of an inherited member)

The C symbol is "sysmlv2_" + rust_fn. Result codes mirror tools/gen_abi.py exactly; the two
generators must agree, and both read the same table, so they do.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

from naming import abi_params, op_key, result_code

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DEFAULT_TABLES = ROOT / "vendor" / "naming-table"  # vendored; see its PIN.json
OUT = ROOT / "python" / "sysml" / "toolkit_table.py"

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tables", type=Path, default=DEFAULT_TABLES)
    a = ap.parse_args()
    raw = (a.tables / "toolkit-api-names.csv").read_bytes()
    digest = hashlib.sha256(raw.replace(b"\r\n", b"\n")).hexdigest()
    rows = list(csv.DictReader(raw.decode("utf-8").splitlines()))
    # Properties are keyed by name, operations by name + "()": `instantiatedType` is both a
    # property and an operation of the same class, and each keeps its row.
    for r in rows:
        r["key"] = op_key(r["member"]) if r["kind"] == "operation" else r["member"]
    mm = json.loads((ROOT / "metamodel.json").read_text(encoding="utf-8"))

    lines = [
        "# Generated by tools/gen_toolkit_table.py. Do not edit.",
        f'NAMES_DIGEST = "{digest}"',
        "FUNCS = {",
    ]
    for r in rows:
        params = tuple(zip([p for p in r["params"].split(";") if p], abi_params(r)))
        lines.append(f'    ({r["declaring_class"]!r}, {r["key"]!r}): ("sysmlv2_{r["rust_fn"]}", {result_code(r)!r}, {params!r}),')
    lines.append("}")
    lines.append("BASES = {")
    for name, rec in sorted(mm["classes"].items()):
        lines.append(f"    {name!r}: {rec['bases']!r},")
    lines.append("}")
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    print(f"wrote {OUT}: {len(rows)} functions, {len(mm['classes'])} classes, digest {digest[:12]}")


if __name__ == "__main__":
    main()
