"""Generate ts/toolkit_table.mjs: the dispatch data the JavaScript SysML Toolkit backend needs.
Same inputs and same result codes as tools/gen_toolkit_table.py.
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

from naming import abi_params, op_key, result_code

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DEFAULT_TABLES = ROOT / "vendor" / "naming-table"  # vendored; see its PIN.json
OUT = ROOT / "ts" / "toolkit_table.mjs"

def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tables", type=Path, default=DEFAULT_TABLES)
    a = ap.parse_args()
    raw = (a.tables / "toolkit-api-names.csv").read_bytes()
    digest = hashlib.sha256(raw.replace(b"\r\n", b"\n")).hexdigest()
    rows = list(csv.DictReader(raw.decode("utf-8").splitlines()))
    # Properties are keyed by name, operations by name + "()": `instantiatedType` is both a
    # property and an operation of the same class, and each keeps its row.
    for r in rows:
        r["key"] = op_key(r["member"]) if r["kind"] == "operation" else r["member"]
    mm = json.loads((ROOT / "metamodel.json").read_text(encoding="utf-8"))

    funcs = {f'{r["declaring_class"]}::{r["key"]}': [f'sysmlv2_{r["rust_fn"]}', result_code(r), ";".join(abi_params(r))] for r in rows}
    bases = {name: rec["bases"] for name, rec in sorted(mm["classes"].items())}
    out = [
        "// Generated by tools/gen_toolkit_table_js.py. Do not edit.",
        f'export const NAMES_DIGEST = "{digest}";',
        "export const FUNCS = " + json.dumps(funcs, separators=(",", ":")) + ";",
        "export const BASES = " + json.dumps(bases, separators=(",", ":")) + ";",
        "",
    ]
    OUT.write_text("\n".join(out), encoding="utf-8", newline="\n")
    print(f"wrote {OUT}: {len(rows)} functions, {len(bases)} classes, digest {digest[:12]}")


if __name__ == "__main__":
    main()
