"""Generate abi/src/generated.rs: one extern "C" function per row of the naming table.

Inputs (vendored under vendor/naming-table/, see its PIN.json; override with --tables):
  toolkit-api-names.csv      every specification member -> rust_fn
  toolkit-delegation-map.csv the operations the SysML Toolkit can answer, and the ones it refuses

Every row gets a function. Each first checks that the element's metaclass has the member, and
answers NOT_APPLICABLE otherwise. Property rows call the generic reader for their result shape
in abi/src/read.rs with the specification name; the reader asks the SysML Toolkit's checked
reader (`property`), which follows the metamodel's redefinitions itself. Operation rows call
`ops::call` in abi/src/ops.rs with the operation's declaring class and name and their arguments;
it invokes the operation through the SysML Toolkit's operation entry point, which refuses what it
cannot run. The naming table's SHA-256 is embedded so a language core can refuse to run against a
library generated from a different table.

From metamodel.json the generator also emits, for a unit test, every class with its ancestors,
to prove the SysML Toolkit's metaclass hierarchy agrees.

Result type per property row, from the table's result_kind / result_shape / result_type:
  element + A            -> Handles
  element + N or R       -> Ref
  primitive Boolean      -> Bool
  primitive Integer      -> Int
  primitive Real|Rational-> Real
  anything else          -> Str  (a primitive array is JSON-encoded in the string)

Operations take their parameter and result types from metamodel.json (tools/naming.py: an
element list is Handles, one element a Handle, a single Boolean a bool, anything else a Str; the
result maps like a property's).
"""
from __future__ import annotations

import argparse
import csv
import hashlib
import json
from pathlib import Path

from naming import abi_params, result_code

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
DEFAULT_TABLES = ROOT / "vendor" / "naming-table"  # vendored; see its PIN.json
OUT = ROOT / "abi" / "src" / "generated.rs"

def result_type(row: dict) -> str:
    return {"H": "Handles", "R": "Ref", "S": "Str", "T": "Str", "B": "Bool", "I": "Int", "F": "Real"}[result_code(row)]


def c_param(name: str, ctype: str) -> tuple[str, str, str | None]:
    """(rust parameter declaration, the ops::Arg passed on, the pointer to check for null)."""
    if ctype == "Handle":
        return f"{name}: Handle", f"ops::Arg::Handle({name})", None
    if ctype == "bool":
        return f"{name}: bool", f"ops::Arg::Bool({name})", None
    if ctype == "Handles":
        return f"{name}: *const Handles", f"ops::Arg::Handles(&*{name})", name
    return f"{name}: *const Str", f"ops::Arg::Str(&*{name})", name


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--tables", type=Path, default=DEFAULT_TABLES)
    ap.add_argument("--out", type=Path, default=OUT)
    a = ap.parse_args()

    names_path = a.tables / "toolkit-api-names.csv"
    names_bytes = names_path.read_bytes()
    digest = hashlib.sha256(names_bytes.replace(b"\r\n", b"\n")).hexdigest()
    rows = list(csv.DictReader(names_bytes.decode("utf-8").splitlines()))

    out = [
        "//! Generated by tools/gen_abi.py from toolkit-api-names.csv. Do not edit.",
        f"//! Naming table SHA-256: {digest}",
        "",
        "#![allow(unused_variables, clippy::not_unsafe_ptr_arg_deref)]",
        "",
        "use crate::{ops, read, Bool, Handle, Handles, Int, Real, Ref, Session, Status, Str};",
        "",
        f'pub const NAMES_DIGEST: &str = "{digest}";',
        "",
    ]
    readers = {"Handles": "handles", "Ref": "reference", "Str": "text", "Bool": "flag", "Int": "integer", "Real": "real"}
    n_ops = 0
    for r in rows:
        fn = r["rust_fn"]
        rt = result_type(r)
        params = [p for p in r["params"].split(";") if p] if r["kind"] == "operation" else []
        cparams = [c_param(p, t) for p, t in zip(params, abi_params(r))]
        if len(cparams) != len(params):
            raise SystemExit(f"{r['declaring_class']}::{r['member']}: {len(params)} parameters in the table, "
                             f"{len(cparams)} in metamodel.json")
        sig_params = ", ".join(["s: *mut Session", "h: Handle"] + [c[0] for c in cparams] + [f"out: *mut {rt}"])
        member = f'{r["declaring_class"]}::{r["member"]}'
        pointers = ["s.is_null()", "out.is_null()"] + [f"{c[2]}.is_null()" for c in cparams if c[2]]
        out.append(f"/// `{member}` ({r['kind']}).")
        out.append("#[no_mangle]")
        out.append(f"pub unsafe extern \"C\" fn sysmlv2_{fn}({sig_params}) -> Status {{")
        out.append(f"    if {' || '.join(pointers)} {{ return Status::InvalidArg; }}")
        out.append("    let s = &mut *s;")
        out.append("    let e = match s.elem(h) { Ok(e) => e, Err(st) => return st };")
        out.append(f'    if let Err(st) = crate::applicable(s, e, "{r["declaring_class"]}", "{r["member"]}") {{ return st; }}')
        if r["kind"] == "property":
            out.append(f'    read::{readers[rt]}(s, e, "{r["member"]}", &mut *out)')
        else:
            n_ops += 1
            args = ", ".join(c[1] for c in cparams)
            out.append(f'    let answer = ops::call(s, e, "{r["declaring_class"]}", "{r["member"]}", &[{args}]);')
            out.append(f'    read::put_{readers[rt]}(s, "{member}()", answer, &mut *out)')
        out.append("}")
        out.append("")

    out += hierarchy_table()
    a.out.write_text("\n".join(out), encoding="utf-8", newline="\n")
    n_props = sum(1 for r in rows if r["kind"] == "property")
    print(f"wrote {a.out}: {len(rows)} functions ({n_props} properties through the readers, "
          f"{n_ops} operations through the SysML Toolkit's operation entry point), digest {digest[:12]}")


def hierarchy_table() -> list[str]:
    mm = json.loads((ROOT / "metamodel.json").read_text(encoding="utf-8"))["classes"]

    def ancestors(n: str, acc: set) -> set:
        for b in mm[n]["bases"]:
            if b not in acc:
                acc.add(b)
                ancestors(b, acc)
        return acc

    out = [
        "/// Every concrete metaclass with its ancestors, from metamodel.json; the unit test in lib.rs",
        "/// checks the SysML Toolkit's `metaclass_conforms` against it.",
        "#[cfg(test)]",
        "pub static HIERARCHY: &[(&str, &[&str])] = &[",
    ]
    for n in sorted(k for k, i in mm.items() if not i["abstract"]):
        anc = ", ".join(f'"{x}"' for x in sorted(ancestors(n, set())))
        out.append(f'    ("{n}", &[{anc}]),')
    out += ["];", ""]
    return out


if __name__ == "__main__":
    main()
